# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewPluginDialogBase(object):
    def setupUi(self, NewPluginDialogBase):
        NewPluginDialogBase.setObjectName("NewPluginDialogBase")
        NewPluginDialogBase.resize(584, 465)
        self.mMapLayerComboBox = QgsMapLayerComboBox(NewPluginDialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(180, 80, 221, 27))
        self.mMapLayerComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.pushButton_oblicz = QtWidgets.QPushButton(NewPluginDialogBase)
        self.pushButton_oblicz.setGeometry(QtCore.QRect(240, 260, 93, 28))
        self.pushButton_oblicz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_oblicz.setObjectName("pushButton_oblicz")
        self.radioButton_roznicawys = QtWidgets.QRadioButton(NewPluginDialogBase)
        self.radioButton_roznicawys.setGeometry(QtCore.QRect(230, 190, 141, 20))
        self.radioButton_roznicawys.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_roznicawys.setObjectName("radioButton_roznicawys")
        self.radioButton_pole = QtWidgets.QRadioButton(NewPluginDialogBase)
        self.radioButton_pole.setGeometry(QtCore.QRect(230, 220, 131, 20))
        self.radioButton_pole.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_pole.setObjectName("radioButton_pole")
        self.textEdit_wyswietla_wyniki = QtWidgets.QTextEdit(NewPluginDialogBase)
        self.textEdit_wyswietla_wyniki.setGeometry(QtCore.QRect(130, 320, 331, 91))
        self.textEdit_wyswietla_wyniki.setObjectName("textEdit_wyswietla_wyniki")
        self.label_wybierzwarstwe_text = QtWidgets.QLabel(NewPluginDialogBase)
        self.label_wybierzwarstwe_text.setGeometry(QtCore.QRect(230, 50, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_wybierzwarstwe_text.setFont(font)
        self.label_wybierzwarstwe_text.setObjectName("label_wybierzwarstwe_text")
        self.label_wybierzoperacje_text = QtWidgets.QLabel(NewPluginDialogBase)
        self.label_wybierzoperacje_text.setGeometry(QtCore.QRect(230, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_wybierzoperacje_text.setFont(font)
        self.label_wybierzoperacje_text.setObjectName("label_wybierzoperacje_text")

        self.retranslateUi(NewPluginDialogBase)
        QtCore.QMetaObject.connectSlotsByName(NewPluginDialogBase)

    def retranslateUi(self, NewPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        NewPluginDialogBase.setWindowTitle(_translate("NewPluginDialogBase", "Nowa Wtyczka"))
        self.pushButton_oblicz.setText(_translate("NewPluginDialogBase", "Oblicz"))
        self.radioButton_roznicawys.setText(_translate("NewPluginDialogBase", "Róznica wysokości"))
        self.radioButton_pole.setText(_translate("NewPluginDialogBase", "Pole powierzchni"))
        self.label_wybierzwarstwe_text.setText(_translate("NewPluginDialogBase", "Wybierz warstwę:"))
        self.label_wybierzoperacje_text.setText(_translate("NewPluginDialogBase", "Wybierz operację:"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewPluginDialogBase = QtWidgets.QDialog()
    ui = Ui_NewPluginDialogBase()
    ui.setupUi(NewPluginDialogBase)
    NewPluginDialogBase.show()
    sys.exit(app.exec_())
